import webpack from 'webpack'
import WebpackDevServer from 'webpack-dev-server'
import { checkBrowsers } from 'react-dev-utils/browsersHelper'
import { choosePort, createCompiler, prepareUrls } from 'react-dev-utils/WebpackDevServerUtils'
import clearConsole from 'react-dev-utils/clearConsole'
import chalk from 'react-dev-utils/chalk'

import mainWebpackConfig from '../webpack.config'
import createDevServerConfig from './w-dev-server'

import { appPath } from '../paths'

const isInteractive = process.stdout.isTTY
process.env.NODE_ENV = 'development'

const DEFAULT_PORT = parseInt(process.env.PORT, 10) || 3000
const HOST = process.env.HOST || '0.0.0.0'

// Makes the script crash on unhandled rejections instead of silently
// ignoring them. In the future, promise rejections that are not handled will
// terminate the Node.js process with a non-zero exit code.
process.on('unhandledRejection', err => {
  throw err
})

checkBrowsers(appPath, isInteractive)
  .then(() => {
    return choosePort(HOST, DEFAULT_PORT)
  })
  .then(port => {
    if (port == null) return

    const protocol = process.env.HTTPS === 'true' ? 'https' : 'http'
    const urls = prepareUrls(protocol, HOST, port)
    const compiler = webpack(mainWebpackConfig)
    // Load proxy config
    // Serve webpack assets generated by the compiler over a web server.
    const serverConfig = createDevServerConfig({}, urls.lanUrlForConfig)
    // @ts-ignore
    const devServer = new WebpackDevServer(compiler, serverConfig)
    // Launch WebpackDevServer.
    devServer.listen(port, HOST, err => {
      if (err) {
        return console.log(err)
      }
      if (isInteractive) {
        clearConsole()
      }
      console.log(chalk.cyan('Starting the development server...\n'))
    })
    // \\
    ;['SIGINT', 'SIGTERM'].forEach(sig => {
      //@ts-ignore
      process.on(sig, () => {
        devServer.close()
        process.exit()
      })
    })
  })
